version: '3.8'
services:
  dcaspt2:
    container_name: 'fortran_devcontainer_sample'
    hostname: 'fortran_devcontainer_sample'
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    tty: true
    # Login as non-root user (docker)
    # because mpirun does not work as root
    # except if --allow-run-as-root option is used
    environment:
      GID: 1000
      UID: 1000
      USER: docker
    user: docker
    volumes:
      - type: bind
        source: ..
        target: /workspace